M48
; DRILL file KiCad 10.0.2 date 2026-07-24T00:13:40
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-07-24T00:13:40-06:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,10.0.2
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.650
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C1.150
%
G90
G05
T1
X120.94Y-90.76
T2
X120.94Y-98.11
M30
