M48
; DRILL file KiCad 10.0.4-10.0.4~ubuntu24.04.1 date 2026-07-22T03:05:35
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-07-22T03:05:35-06:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,10.0.4-10.0.4~ubuntu24.04.1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.650
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C1.150
%
G90
G05
T1
X120.94Y-90.76
T2
X120.94Y-98.11
M30
